In [2]:
import numpy as np

In [4]:
# Перемножить матрицы 5x3 и 3x2
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html
ar = np.dot(np.ones((5,3)), np.ones((3,2)))
print(ar)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [6]:
# Дан массив, поменять знак у элементов, значения которых между 3 и 8
ar = np.arange(11)
print(ar)
ar[(3 < ar) & (ar <= 8)] *= -1
print(" ")
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10]
 
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [7]:
# Создать 5x5 матрицу со значениями в строках от 0 до 4
ar = np.zeros((5,5))
ar = ar + np.arange(5)
print(ar)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [10]:
# Есть генератор, сделать с его помощью массив
# https://habr.com/ru/post/132554/     yield, what is it?
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [11]:
# Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое
# 12 чисел от 0 до 1 включительно дальше крайние удаляем
ar = np.linspace(0,1,12)[1:-1]
print(ar)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [12]:
# Отсортировать вектор
vec = np.random.random(10)
vec.sort()
print(vec)

[0.02308047 0.03919108 0.12698835 0.13406947 0.29817788 0.61254957
 0.72752934 0.86655503 0.87853305 0.96607296]


In [14]:
# Проверить, одинаковы ли 2 numpy массива
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B) # Returns True if the two arrays are equal within the given tolerance; False otherwise.
print(equal)

False


In [15]:
# Сделать массив неизменяемым
ar = np.zeros(10)
ar.flags.writeable = False
ar[0] = 1 # exception on this step


ValueError: assignment destination is read-only

In [17]:
# Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную
ar = np.random.random((10,2))
X,Y = ar[:,0], ar[:,1]
R = np.hypot(X, Y)
T = np.arctan2(Y,X)
print(R)
print(" ")
print(T)

[0.53468988 0.38406678 0.76457727 0.63376343 0.80506499 0.96753045
 0.6029739  0.49787615 0.80271242 0.70402335]
 
[0.98599556 1.55050011 0.15199257 0.30410978 0.97175392 0.11080536
 1.46542522 1.46178092 0.78567129 0.06464607]


In [20]:
# Заменить максимальный элемент на ноль
ar = np.random.random(10)
print(ar)
print(" ")
ar[ar.argmax()] = 0
print(ar)

[0.16357027 0.14318941 0.43722655 0.57718923 0.04913793 0.46021887
 0.28239119 0.0971424  0.87555655 0.65182124]
 
[0.16357027 0.14318941 0.43722655 0.57718923 0.04913793 0.46021887
 0.28239119 0.0971424  0.         0.65182124]


In [23]:
# Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]
ar = np.zeros((10,10), [('x',float),('y',float)])

ar['x'], ar['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))

print(ar)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [24]:
# Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [26]:
# Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
   print(" ")
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)
   print(" ")

-128
127
 
-2147483648
2147483647
 
-9223372036854775808
9223372036854775807
 
-3.4028235e+38
3.4028235e+38
1.1920929e-07
 
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
 


In [40]:
#  Напечатать все значения в массиве
np.set_printoptions(threshold=500)
Z = np.zeros((15,15))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [42]:
# Найти ближайшее к заданному значению число в заданном массиве
Z = np.arange(100)
print(Z)
print(" ")
v = np.random.uniform(0,100)
print(v)
print(" ")
index = (np.abs(Z-v)).argmin()
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
 
91.93999371488069
 
92


In [46]:
# Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)
ar = np.zeros(10, [ ('pos', [ ('x', float, 1), ('y', float, 1)]),('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print(ar)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Program Files\Python37\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [48]:
# Дан массив (100,2) координат, найти расстояние от каждой точки до каждой
import scipy.spatial as sp

ar = np.random.random((10,2))
print(ar)
print(" ")
D = sp.distance.cdist(ar,ar)
print(D)

[[0.         0.60786152 0.82586204 0.52560694 0.43971184 0.81558327
  0.41391417 0.31439959 0.12586725 0.49701404]
 [0.60786152 0.         0.49814151 0.73010289 0.30920896 0.20778545
  0.5516008  0.52836851 0.7302612  0.38511073]
 [0.82586204 0.49814151 0.         0.56855936 0.39471962 0.51323426
  0.48404011 0.91971378 0.90932807 0.32989887]
 [0.52560694 0.73010289 0.56855936 0.         0.4210586  0.8854681
  0.1830145  0.79305807 0.53047202 0.35608898]
 [0.43971184 0.30920896 0.39471962 0.4210586  0.         0.47864001
  0.24292285 0.53788421 0.53757741 0.1005302 ]
 [0.81558327 0.20778545 0.51323426 0.8854681  0.47864001 0.
  0.71746845 0.71656983 0.93761899 0.52940032]
 [0.41391417 0.5516008  0.48404011 0.1830145  0.24292285 0.71746845
  0.         0.63970859 0.459384   0.19729469]
 [0.31439959 0.52836851 0.91971378 0.79305807 0.53788421 0.71656983
  0.63970859 0.         0.4124657  0.63061295]
 [0.12586725 0.7302612  0.90932807 0.53047202 0.53757741 0.93761899
  0.459384   0.412465

In [50]:
# Преобразовать массив из float в int
ar = np.arange(10, dtype=np.int32)
print(ar)
ar = ar.astype(np.float32, copy=False) #https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html
print(ar)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [51]:
# Дан файл:
# Как прочитать его?
#1,2,3,4,5
#6,,,7,8
#,,9,10,11
#
# ar = np.genfromtxt("missing.dat", delimiter=",")

SyntaxError: invalid syntax (<ipython-input-51-1a88305eacc9>, line 3)

In [53]:
# Каков эквивалент функции enumerate для numpy массивов?
ar = np.arange(9).reshape(3,3)
print(ar)
print(" ")
for index, value in np.ndenumerate(ar):
    print(index, value)
print(" ")
for index in np.ndindex(ar.shape):
    print(index, ar[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
 
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [54]:
# Сформировать 2D массив с распределением Гаусса
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.hypot(X, Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [58]:
# Случайно расположить p элементов в 2D массив
n = 10
p = 5
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 8)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8. 0. 0.]
 [8. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [60]:
# Отнять среднее из каждой строки в матрице
ar = np.random.rand(5, 10)
print(ar)
print(" ")
Y = ar - ar.mean(axis=1, keepdims=True)
print(Y)

[[0.14803785 0.04808598 0.4213462  0.47957879 0.19343901 0.55485448
  0.69879778 0.8883507  0.18159202 0.63418316]
 [0.04079789 0.05040735 0.60323277 0.36458369 0.53477655 0.03491313
  0.94807677 0.21720208 0.62766436 0.99661059]
 [0.32869368 0.38696122 0.27930902 0.27874598 0.66517681 0.38622879
  0.99428043 0.47967772 0.1055     0.39034119]
 [0.01014583 0.76321627 0.23992582 0.64672474 0.76801771 0.36039509
  0.50023223 0.17653219 0.31333564 0.36293307]
 [0.90069646 0.6785907  0.80662225 0.05050321 0.45533244 0.36061281
  0.69741707 0.59291314 0.32216904 0.35832299]]
 
[[-0.27678875 -0.37674062 -0.0034804   0.05475219 -0.23138758  0.13002788
   0.27397118  0.4635241  -0.24323458  0.20935657]
 [-0.40102862 -0.39141916  0.16140625 -0.07724283  0.09295003 -0.40691339
   0.50625025 -0.22462444  0.18583784  0.55478407]
 [-0.10079781 -0.04253026 -0.15018247 -0.1507455   0.23568533 -0.04326269
   0.56478894  0.05018623 -0.32399148 -0.03915029]
 [-0.40400003  0.34907041 -0.17422004  0.232578

In [62]:
# Отсортировать матрицу по n-ому столбцу
ar = np.random.randint(0,10,(3,3))
n = 1  
print(ar)
print(" ")
print(ar[ar[:,n].argsort()])

[[1 4 2]
 [5 3 7]
 [9 3 6]]
 
[[5 3 7]
 [9 3 6]
 [1 4 2]]


In [65]:
# Определить, есть ли в 2D массиве нулевые столбцы
ar = np.random.randint(0,3,(3,10))
print(ar)
print(" ")
print((~ar.any(axis=0)).any())

[[1 1 2 2 0 1 0 1 0 2]
 [1 2 2 2 1 2 0 2 2 0]
 [0 0 1 0 1 2 0 1 1 2]]
 
True


In [68]:
# Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)
ar = np.ones(10)
print(ar)
print(" ")
I = np.random.randint(0,len(ar),20)
print(I)
print(" ")
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 
[9 6 0 5 3 0 4 9 2 1 8 3 9 9 8 8 0 4 7 2]
 
[[10.  7.  9.  5.  5.  6.  3.  6.  5.  4.]
 [10.  7.  9.  5.  5.  6.  3.  6. 13.  4.]
 [10.  7.  9.  5.  5.  6.  3. 14.  5.  4.]
 [18.  7.  9.  5.  5.  6.  3.  6.  5.  4.]
 [10.  7.  9.  5.  5.  6.  3.  6.  5.  4.]
 [10.  7.  9. 13.  5.  6.  3.  6.  5.  4.]
 [10.  7.  9.  5.  5.  6.  3.  6.  5.  4.]
 [10.  7.  9.  5.  5.  6.  3.  6.  5.  4.]
 [10.  7. 17.  5.  5.  6.  3.  6.  5.  4.]
 [10.  7.  9.  5.  5.  6.  3.  6.  5.  4.]]


In [69]:
# Дан массив (w,h,3) (картинка) dtype = ubyte, посчитать количество различных цветов
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [70]:
# Дан четырехмерный массив, посчитать сумму по последним двум осям
ar = np.random.randint(0,10, (3,4,3,4))
print(ar)
print(" ")
sum = ar.reshape(ar.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[3 4 8 6]
   [9 8 9 5]
   [1 7 3 9]]

  [[8 9 2 8]
   [1 5 9 3]
   [0 1 0 6]]

  [[8 0 6 7]
   [1 7 9 2]
   [2 8 0 5]]

  [[0 9 7 2]
   [0 4 1 3]
   [9 3 6 5]]]


 [[[4 7 1 5]
   [5 0 8 5]
   [2 7 6 2]]

  [[1 6 6 8]
   [5 9 7 4]
   [8 8 6 4]]

  [[8 5 3 9]
   [1 1 7 4]
   [9 7 5 8]]

  [[4 0 3 5]
   [6 8 0 4]
   [6 3 6 0]]]


 [[[5 4 9 4]
   [0 2 7 0]
   [1 5 6 4]]

  [[4 8 2 4]
   [9 9 3 9]
   [2 9 0 6]]

  [[6 0 7 1]
   [8 2 8 1]
   [5 2 4 1]]

  [[4 6 0 0]
   [5 6 2 1]
   [7 7 6 8]]]]
 
[[72 52 55 49]
 [52 72 67 45]
 [47 65 45 52]]


In [77]:
# Найти диагональные элементы произведения матриц
# Slow version
A = np.eye(3)
print(A)
B = np.arange(9).reshape(3,3)
print(B)
x = np.diag(np.dot(A, B))
print(x)
print(" ")
# Fast version
y = np.sum(A * B.T, axis=1)
print(y)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0. 4. 8.]
 
[0. 4. 8.]
