In [1]:
# Импортировать NumPy под именем np
import numpy as np

In [29]:
# Напечатать версию и конфигурацию
print(np.__version__)
np.show_config()

1.17.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [4]:
# Создать вектор (одномерный массив) размера 10, заполненный нулями
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
# Создать вектор размера 10, заполненный единицами
vec = np.ones(10)
print(vec)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
# Создать вектор размера 10, заполненный числом 2.5
vec = np.full(10, 2.5)
print(vec)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [ ]:
# Как получить документацию о функции numpy.add из командной строки?
# python3 -c "import numpy; numpy.info(numpy.add)" 

In [ ]:
# Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1
vec = np.zeros(10)
vec[4] = 1
print(vec)

In [26]:
# Создать вектор со значениями от 10 до 49
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
# Развернуть вектор (первый становится последним)
vec = np.arange(50)
print(vec)
print(" ")
vec = vec[::-1]
print(vec)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
 
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [9]:
# Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
ar = np.arange(9).reshape(3,3)
print(ar)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# Найти индексы ненулевых элементов в [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [11]:
# Создать 3x3 единичную матрицу
ar = np.eye(3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# Создать массив 3x3x3 со случайными значениями
Ar = np.random.random((3,3,3))
print(Ar)

[[[0.59545656 0.17439957 0.64507793]
  [0.76593849 0.45201436 0.86842651]
  [0.80665712 0.72933956 0.14090023]]

 [[0.06727862 0.70179144 0.68318069]
  [0.41686022 0.01069798 0.86969996]
  [0.99106557 0.41297434 0.74222931]]

 [[0.66799152 0.81144257 0.15313797]
  [0.57038636 0.89253422 0.64782319]
  [0.73879199 0.90256211 0.97267585]]]


In [15]:
# Создать массив 10x10 со случайными значениями, найти минимум и максимум
ar = np.random.random((10,10))
print(ar)
arMin, arMax = ar.min(), ar.max()
print(arMin, arMax)

[[9.96076452e-01 4.23692522e-01 3.65021709e-02 8.93855758e-02
  3.97566622e-02 7.36668171e-01 7.41938748e-01 2.10430720e-01
  9.59946359e-01 1.22118769e-01]
 [4.64244854e-01 9.85174894e-01 2.73043993e-01 2.35026571e-01
  7.06867641e-01 6.40435835e-01 1.41890737e-01 2.51164781e-01
  6.34748269e-01 7.73091352e-01]
 [9.75718713e-01 4.59155607e-01 2.98483240e-01 7.45303418e-01
  2.76918327e-01 4.00780326e-01 7.00923461e-01 9.80056022e-01
  6.05591374e-01 1.86803403e-01]
 [1.38392227e-01 8.89332698e-01 6.95344526e-01 3.33316376e-01
  7.12974153e-01 6.87739299e-01 4.91513281e-01 8.26155380e-01
  2.63023208e-01 2.48498952e-01]
 [3.44881361e-01 6.50937960e-01 8.98130019e-01 3.62947331e-01
  6.78297786e-01 9.90449617e-01 2.40540919e-03 4.15236339e-01
  8.49110367e-02 2.07880873e-01]
 [1.26648715e-02 4.52835785e-01 2.19796246e-01 5.73447046e-01
  8.54279473e-01 1.23790828e-01 8.94032294e-02 5.99586936e-01
  5.23630058e-02 7.20448366e-01]
 [4.14758557e-01 3.05469936e-01 1.90913869e-02 5.75931717e

In [17]:
# Создать случайный вектор размера 30 и найти среднее значение всех элементов
vec = np.random.random(30)
print(vec)
m = vec.mean()
print(m)

[0.20265264 0.44583381 0.48289883 0.25068668 0.71871917 0.19434365
 0.18358075 0.77879305 0.11705681 0.16414427 0.08627921 0.18272969
 0.70008523 0.75903736 0.4133692  0.66538673 0.30390018 0.80948029
 0.96190447 0.43684901 0.12414889 0.96667161 0.52519574 0.08817832
 0.49000637 0.59611817 0.97462337 0.65209972 0.41616936 0.51620693]
0.4735716498353984


In [19]:
# Создать матрицу с 0 внутри, и 1 на границах
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [20]:
# Выяснить результат следующих выражений
Z = 0 * np.nan
print(Z)
Z = np.nan == np.nan
print(Z)
Z = np.inf > np.nan
print(Z)
Z = np.nan - np.nan
print(Z)
Z = 0.3 == 3 * 0.1
print(Z)

nan
False
False
nan
False


In [22]:
# Создать 5x5 матрицу с 1,2,3,4 под диагональю
# https://www.w3resource.com/numpy/array-creation/diag.php
Z = np.diag(np.arange(1, 5), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [23]:
# Создать 8x8 матрицу и заполнить её в шахматном порядке
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
