In [2]:
import numpy as np

In [17]:
# Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением
vec = np.array([1,2,3,4,5])
print(vec)
nz = 3
newVec = np.zeros((len(vec)-1)*(nz)+len(vec))
newVec[::nz+1] = vec
print(newVec)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [6]:
# Поменять 2 строки в матрице
ar = np.arange(25).reshape(5,5)
print(ar)
print(" ")
ar[[0,1]] = ar[[1,0]]
print(ar)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
 
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [9]:
# Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники
triangles = np.random.randint(0,100,(10,3))
print(triangles)
print(" ")
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
print(F)
print(" ")
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[[40 69 58]
 [79 93 60]
 [70  0 60]
 [64 48 90]
 [44 47 12]
 [73 50 74]
 [76  1 22]
 [30 55 63]
 [21 51 42]
 [12 32 10]]
 
[[56 16 16 49 49 56]
 [25 80 80  3  3 25]
 [70 43 43 87 87 70]
 [64 71 71 60 60 64]
 [ 4 26 26  4  4  4]
 [46 22 22 14 14 46]
 [51 13 13 87 87 51]
 [43 96 96 35 35 43]
 [93 19 19 41 41 93]
 [42 98 98 97 97 42]]
 
[( 3, 25) ( 3, 80) ( 4,  4) ( 4, 26) (13, 51) (13, 87) (14, 22) (14, 46)
 (16, 49) (16, 56) (19, 41) (19, 93) (22, 46) (25, 80) (35, 43) (35, 96)
 (41, 93) (42, 97) (42, 98) (43, 70) (43, 87) (43, 96) (49, 56) (51, 87)
 (60, 64) (60, 71) (64, 71) (70, 87) (97, 98)]


In [11]:
# Дан массив C; создать массив A, что np.bincount(A) == C
C = np.bincount([1,1,2,3,4,4,6])
print(C)
print(" ")
A = np.repeat(np.arange(len(C)), C)
print(A)
print(" ")
print(np.bincount(A))# повоторение чисел

[0 2 1 1 2 0 1]
 
[1 1 2 3 4 4 6]
 
[0 2 1 1 2 0 1]


In [15]:
# Посчитать среднее, используя плавающее окно
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float) # кумулятивная сумма 
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

r = np.arange(20)
print(r)
print(" ")
print(moving_average(r))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [17]:
# Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
#Create a view into the array with the given shape and strides.

r = np.arange(10)
print(r)
print(" ")
Vec = rolling(r, 3)

print(Vec)

[0 1 2 3 4 5 6 7 8 9]
 
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [20]:
# Инвертировать булево значение, или поменять знак у числового массива без создания нового
Z = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

array([[-1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [21]:
# Рассмотрим 2 набора точек P0, P1 описания линии (2D) и точку р, как вычислить расстояние от р до каждой линии i (P0[i],P1[i])
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.41025275  3.33104803  2.05760477  6.17618081  1.00711115 12.43783585
  6.72916535  5.49887869  4.23745659  3.14232545]


In [22]:
#Дан массив. Написать функцию, выделяющую часть массива фиксированного размера с центром в данном элементе (дополненное значением fill если необходимо)
Z = np.random.randint(0,10, (10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P - Rs//2)
Z_stop  = (P + Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 4 0 8 5 1 4 0 0 4]
 [7 8 7 5 4 3 6 3 7 4]
 [8 0 1 2 7 4 3 9 7 1]
 [1 5 7 3 9 2 0 8 4 1]
 [2 9 2 1 5 9 3 5 5 0]
 [4 3 9 1 6 7 6 9 3 4]
 [0 6 7 6 1 6 6 8 2 8]
 [4 5 7 0 6 9 4 6 8 0]
 [6 5 6 4 7 5 5 6 9 0]
 [8 1 1 5 0 4 9 9 3 0]]
[[0 0 0 0 0]
 [0 2 4 0 8]
 [0 7 8 7 5]
 [0 8 0 1 2]
 [0 1 5 7 3]]


C:\Program Files\Python37\lib\site-packages\ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [26]:
#Посчитать ранг матрицы
Z = np.random.uniform(0,1,(10,10))

rank = np.linalg.matrix_rank(Z)
print(rank)

10


In [28]:
# Найти наиболее частое значение в массиве
Z = np.random.randint(0,10,50)
print(Z)
print(" ")
print(np.bincount(Z).argmax())

[2 6 0 1 1 7 5 4 7 3 2 7 3 5 5 5 9 6 5 3 5 1 0 6 2 6 3 3 7 7 6 8 9 9 0 7 2
 7 0 6 9 6 8 6 4 5 0 7 4 1]
 
6


In [30]:
# Извлечь все смежные 3x3 блоки из 10x10 матрицы
Z = np.random.randint(0,5,(10,10))
print(Z)
print(" ")
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[4 1 3 1 3 1 4 1 1 0]
 [0 3 4 0 3 3 3 0 4 2]
 [0 3 2 3 2 2 1 1 4 0]
 [4 2 2 3 2 4 2 2 3 3]
 [2 2 4 0 2 0 2 1 3 1]
 [3 1 2 2 1 3 3 1 4 3]
 [1 0 4 4 4 0 2 4 3 4]
 [4 4 1 3 1 2 3 4 2 4]
 [4 0 3 0 4 2 1 3 4 4]
 [0 1 4 0 1 2 0 3 3 0]]
 
[[[[4 1 3]
   [0 3 4]
   [0 3 2]]

  [[1 3 1]
   [3 4 0]
   [3 2 3]]

  [[3 1 3]
   [4 0 3]
   [2 3 2]]

  [[1 3 1]
   [0 3 3]
   [3 2 2]]

  [[3 1 4]
   [3 3 3]
   [2 2 1]]

  [[1 4 1]
   [3 3 0]
   [2 1 1]]

  [[4 1 1]
   [3 0 4]
   [1 1 4]]

  [[1 1 0]
   [0 4 2]
   [1 4 0]]]


 [[[0 3 4]
   [0 3 2]
   [4 2 2]]

  [[3 4 0]
   [3 2 3]
   [2 2 3]]

  [[4 0 3]
   [2 3 2]
   [2 3 2]]

  [[0 3 3]
   [3 2 2]
   [3 2 4]]

  [[3 3 3]
   [2 2 1]
   [2 4 2]]

  [[3 3 0]
   [2 1 1]
   [4 2 2]]

  [[3 0 4]
   [1 1 4]
   [2 2 3]]

  [[0 4 2]
   [1 4 0]
   [2 3 3]]]


 [[[0 3 2]
   [4 2 2]
   [2 2 4]]

  [[3 2 3]
   [2 2 3]
   [2 4 0]]

  [[2 3 2]
   [2 3 2]
   [4 0 2]]

  [[3 2 2]
   [3 2 4]
   [0 2 0]]

  [[2 2 1]
   [2 4 2]
   [2 0 2]]

  [[2 1 1]
   [4 2 2]
   [0 

In [32]:
# Создать подкласс симметричных 2D массивов (Z[i,j] == Z[j,i])
---

SyntaxError: invalid syntax (<ipython-input-32-52eb39c9f94c>, line 3)

In [33]:
# Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [35]:
# Дан массив 16x16, посчитать сумму по блокам 4x4
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [36]:
# Написать игру "жизнь"
def iterate(Z):
    # Число соседей
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Применим правила
    birth = (N == 3) & (Z[1:-1,1:-1]==0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100):
    print(Z)
    Z = iterate(Z)

[[0 0 0 ... 1 1 1]
 [0 0 0 ... 1 0 1]
 [0 1 0 ... 0 1 0]
 ...
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [1 0 1 ... 1 0 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 1 0 ... 1 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

In [37]:
# Найти n наибольших значений в массиве
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9999 9997 9996 9998 9995]


In [38]:
# Построить прямое произведение массивов (все комбинации с каждым элементом)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [16]:
# Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B
A = np.random.randint(0,5,(8,3))
print(A)
print(" ")
B = np.random.randint(0,5,(2,2))
print(B)
print(" ")

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[[0 3 1]
 [4 2 1]
 [0 0 3]
 [3 0 0]
 [3 1 4]
 [2 1 3]
 [2 3 3]
 [2 2 3]]
 
[[0 0]
 [3 2]]
 
[0 2 3 5 6 7]


In [15]:
# Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])
ar = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(ar[:,1:] == ar[:,:-1], axis=1)
U = ar[~E]
print(ar)
print(" ")
print(U)

[[1 3 1]
 [1 3 1]
 [0 1 3]
 [0 2 4]
 [4 0 2]
 [2 3 4]
 [3 3 0]
 [3 2 0]
 [0 3 2]
 [4 1 1]]
 
[[1 3 1]
 [1 3 1]
 [0 1 3]
 [0 2 4]
 [4 0 2]
 [2 3 4]
 [3 3 0]
 [3 2 0]
 [0 3 2]
 [4 1 1]]


In [41]:
# Преобразовать вектор чисел в матрицу бинарных представлений
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [10]:
# Дан двумерный массив. Найти все различные строки
Z = np.random.randint(0, 2, (6,3))
print(Z)
print(" ")
arr = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(arr, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 1]]
 
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]]


In [8]:
# Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul
A = np.arange(10)
print(A)
print(" ")
B = np.arange(10)
np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j', A, B)    # np.outer(A, B)o read: http://ajcr.net/Basic-guide-to-einsum/

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j', A, B)    # np.outer(A, B)

[0 1 2 3 4 5 6 7 8 9]
 


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])